/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fslfquzqhewrdwhqgmae"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbGZxdXpxaGV3cmR3aHFnbWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MDIxMTksImV4cCI6MjA5MDI3ODExOX0.sQe8-TzCeya_re2EJ-DqCzXABRlJoxGQg9HWbs6Kpns"